name: ML4Litho
channels:
  - defaults
dependencies:
  - zipfile36
  - matplotlib
  - scikit-learn
  - numpy
  - pandas
  - tensorboard >= 1.12
  - tensorflow >= 1.12
  - pip:
    - beholder
    - jupyter-tensorboard
